### ISSUE TITLE
Grammar/spelling issues

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/careers-managing-your-job-search#3]
Need a period at the end of this sentence:
"There are two kinds of job seekers: passive and active

Job seeker is two words everywhere on this page except for the following two sentences:
"You don’t want to be this kind of jobseeker."
"As a jobseeker, you can also think about conversion rates as a way to measure your progress."

Thank you.

**Comment by maxwellbenton** [comment]
Fixed, thank you @ValerieHMoore!
