### ISSUE TITLE
More grammar/spelling issues

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/careers-managing-your-job-search#4]
The close quote should be after the period in this sentence:
Another term salespeople use is “conversion rate”. 

This sentence has a missing antecedent:
"Conversion rates are often used as a benchmark to see if they’re on track with hitting their goals."

Suggested edit:
"Conversion rates are often used by salespeople as a benchmark to see if they’re on track with hitting their goals."

Thank you.

**Comment by maxwellbenton** [comment]
Fixed, thank you @ValerieHMoore!
